[package]
name = "cealign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdbtbx = "0.11"
plotters = "0.3"
regex = "1.10"
nalgebra = "0.33"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
